<?php

namespace AppBundle\Repository;

/**
 * ShellRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShelfRepository extends \Doctrine\ORM\EntityRepository
{
}
